# This is a basic workflow to help you get started with Actions

name: Build & Deploy Packer Template

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - main
    paths:
      - 'packer/main.pkr.hcl'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the packer template and deploy to AWS
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run Packer Container - Build & Deploy
      # pull official hashicorp packer container for docker hub
      uses: docker://diegoaceneves/packer-ansible
      env: # Grab the AWS environment variables for deployment
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_GITHUB_TOKEN: ${{ secrets.AWS_GITHUB_TOKEN }}
      with:
        args: "build /github/workspace/packer/main.pkr.hcl"